## Welcome to the SolPOC Notebook !
### In a way to pick up the software, we propose you to learn and test the key features in a way to be familiar with the software before usage.
<br>

# Chapter 1 : Reflectivity, transmissivity and absorptivity

In optics, three important values are the Reflectivity (noted R), the Transmissivity (noted T) and the Abosrption (noted A). Let's see how the software is calculating them :

- Based on the Abélès matrix formalism, the RTA3C and RTA functions are calculating R, T, A. For that, these functions only need an array of wavelengths, a stack thickness, the real and complex part of material refraction indexes and the incidence angle of the radiation in degrees.

To test this functionality, let's try with some values.

First, let's run the functions file:

In [4]:
run functions_COPS.py

Now, let's create the variables needed !

Linked with what we were saying before, Wl (for the wavelength) is an array that covers all the desired wavelengths, in nm. For an easy example, let's make a range of wavelengths between 400 and 600 nm with a step of 10 (400, 410, 420, ..., 600) :

In [5]:
Wl = np.arange(400, 610, 10)
print(Wl)

[400 410 420 430 440 450 460 470 480 490 500 510 520 530 540 550 560 570
 580 590 600]


Now, let's create an easy thickness stack where the substrate has 1 000 000 nm of thickness and each material 100 nm. The stack thicknesses is a list called d :

In [12]:
d = [[1000000, 100, 100]]

In addition, we have to create arrays with the reals and complex refactive index of the materials. For this example, let's put some refractive indexes :

In [13]:
n = np.zeros((len(Wl), 3))
n[:,0] = np.arange(1.55, 1.49975, -0.0025)
n[:,1] = np.arange(3, 2.6985, -0.015)
n[:,2] = np.arange(1.8, 1.4985, -0.015)
k = np.zeros((len(Wl), 3))
k[:, 0] = 0
k[:, 1] = np.arange(0.1, 0.0799, -0.001)
k[:, 2] = np.arange(0.1, 0.0475, -0.0025)

We get :

In [14]:
print('n = \n', n)
print('\nk = \n', k)

n = 
 [[1.55   3.     1.8   ]
 [1.5475 2.985  1.785 ]
 [1.545  2.97   1.77  ]
 [1.5425 2.955  1.755 ]
 [1.54   2.94   1.74  ]
 [1.5375 2.925  1.725 ]
 [1.535  2.91   1.71  ]
 [1.5325 2.895  1.695 ]
 [1.53   2.88   1.68  ]
 [1.5275 2.865  1.665 ]
 [1.525  2.85   1.65  ]
 [1.5225 2.835  1.635 ]
 [1.52   2.82   1.62  ]
 [1.5175 2.805  1.605 ]
 [1.515  2.79   1.59  ]
 [1.5125 2.775  1.575 ]
 [1.51   2.76   1.56  ]
 [1.5075 2.745  1.545 ]
 [1.505  2.73   1.53  ]
 [1.5025 2.715  1.515 ]
 [1.5    2.7    1.5   ]]

k = 
 [[0.     0.1    0.1   ]
 [0.     0.099  0.0975]
 [0.     0.098  0.095 ]
 [0.     0.097  0.0925]
 [0.     0.096  0.09  ]
 [0.     0.095  0.0875]
 [0.     0.094  0.085 ]
 [0.     0.093  0.0825]
 [0.     0.092  0.08  ]
 [0.     0.091  0.0775]
 [0.     0.09   0.075 ]
 [0.     0.089  0.0725]
 [0.     0.088  0.07  ]
 [0.     0.087  0.0675]
 [0.     0.086  0.065 ]
 [0.     0.085  0.0625]
 [0.     0.084  0.06  ]
 [0.     0.083  0.0575]
 [0.     0.082  0.055 ]
 [0.     0.081  0.0525]
 [

Finally, we take need a value for the incidence angle, 0 degree is for a normal incidence angle !

In [15]:
Ang = 0

Now, we can calculate the Reflectivity, Transmissivity and Absorptivity using RTA() function !

In [17]:
R, T, A = RTA(Wl, d, n, k, Ang)
print('R = ', R)
print('T = ', T)
print('A = ', A)

R =  [0.28825651 0.26116543 0.22438712 0.18128399 0.13577424 0.09219523
 0.05473638 0.02657622 0.0091236  0.0017938  0.00244313 0.00819122
 0.01621645 0.02426074 0.03081132 0.03506253 0.03677815 0.03613561
 0.03358965 0.02976433 0.02536941]
T =  [0.31416556 0.33426878 0.36177426 0.39565577 0.43426356 0.47523257
 0.51568056 0.55273067 0.5841806  0.60899397 0.62737591 0.64045536
 0.64979735 0.656973   0.66329524 0.66971426 0.6768173  0.68487812
 0.69392079 0.70378128 0.714162  ]
A =  [0.39757793 0.40456579 0.41383863 0.42306024 0.4299622  0.4325722
 0.42958306 0.42069311 0.4066958  0.38921223 0.37018096 0.35135343
 0.33398621 0.31876626 0.30589344 0.29522321 0.28640455 0.27898627
 0.27248956 0.26645439 0.26046859]


We can notice that the function returns 3 arrays (1 for R, 1 for T, 1 for A) that will help us to resolve optical problems. The array length is the same as Wl and noted as the energy conservation law R[i] + T[i] + A[i] = 1.

To conclude this 1st chapter, we just let you know that the sister function RTA3C exists. RTA3C exists for academic purposes : 
i) It calculates RTA just for 3 layers
ii) The code is easier to understand than RTA but much slower...

In [19]:
R, T, A = RTA3C(Wl, d, n, k, Ang)
print('R = ', R)
print('T = ', T)
print('A = ', A)

R =  [0.28825651 0.26116543 0.22438712 0.18128399 0.13577424 0.09219523
 0.05473638 0.02657622 0.0091236  0.0017938  0.00244313 0.00819122
 0.01621645 0.02426074 0.03081132 0.03506253 0.03677815 0.03613561
 0.03358965 0.02976433 0.02536941]
T =  [0.31416556 0.33426878 0.36177426 0.39565577 0.43426356 0.47523257
 0.51568056 0.55273067 0.5841806  0.60899397 0.62737591 0.64045536
 0.64979735 0.656973   0.66329524 0.66971426 0.6768173  0.68487812
 0.69392079 0.70378128 0.714162  ]
A =  [0.39757793 0.40456579 0.41383863 0.42306024 0.4299622  0.4325722
 0.42958306 0.42069311 0.4066958  0.38921223 0.37018096 0.35135343
 0.33398621 0.31876626 0.30589344 0.29522321 0.28640455 0.27898627
 0.27248956 0.26645439 0.26046859]


We can observe that the results are the same than RTA ones. Just for trying, let's add one more layer and see !

In [20]:
n = np.zeros((len(Wl), 4))
n[:,0] = np.arange(1.55, 1.49975, -0.0025)
n[:,1] = np.arange(3, 2.6985, -0.015)
n[:,2] = np.arange(1.8, 1.4985, -0.015)
n[:, 3] = np.arange(1.8, 1.4985, -0.015)
k = np.zeros((len(Wl), 4))
k[:, 0] = 0
k[:, 1] = np.arange(0.1, 0.0799, -0.001)
k[:, 2] = np.arange(0.1, 0.0475, -0.0025)
k[:, 3] = np.arange(0.1, 0.0475, -0.0025)
d = [[1000000, 100, 100, 100]]

We added a new layer !

In [21]:
R, T, A = RTA3C(Wl, d, n, k, Ang)
print('R = ', R)
print('T = ', T)
print('A = ', A)

R =  [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]
T =  [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]
A =  [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan]


C:\Users\titou\Downloads\COPS-main (2)\COPS-main\COPS\functions_COPS.py:181: RuntimeWarning: invalid value encountered in divide
  rs = (q0PolaS*m11s-qSPolaS*m22s+q0PolaS*qSPolaS*m12s-m21s)/(q0PolaS*m11s+qSPolaS*m22s+q0PolaS*qSPolaS*m12s+m21s)
C:\Users\titou\Downloads\COPS-main (2)\COPS-main\COPS\functions_COPS.py:182: RuntimeWarning: invalid value encountered in divide
  rp = (q0PolaP*m11p-qSPolaP*m22p+q0PolaP*qSPolaP*m12p-m21p)/(q0PolaP*m11p+qSPolaP*m22p+q0PolaP*qSPolaP*m12p+m21p)
C:\Users\titou\Downloads\COPS-main (2)\COPS-main\COPS\functions_COPS.py:183: RuntimeWarning: divide by zero encountered in divide
  ts = 2*q0PolaS/(q0PolaS*m11s+qSPolaS*m22s+q0PolaS*qSPolaS*m12s+m21s)
C:\Users\titou\Downloads\COPS-main (2)\COPS-main\COPS\functions_COPS.py:183: RuntimeWarning: invalid value encountered in divide
  ts = 2*q0PolaS/(q0PolaS*m11s+qSPolaS*m22s+q0PolaS*qSPolaS*m12s+m21s)
C:\Users\titou\Downloads\COPS-main (2)\COPS-main\COPS\functions_COPS.py:184: RuntimeWarning: divide by zero enc

It works with RTA. The function doesn't have a limitation in the layer number and works for 100/120/150 thin layers. We recommand to avoid a number of layers higher than 150 as written in the article.

In [22]:
R, T, A = RTA(Wl, d, n, k, Ang)
print('R = ', R)
print('T = ', T)
print('A = ', A)

R =  [0.16360245 0.10813673 0.05306543 0.01360362 0.00035694 0.01347982
 0.04346139 0.07774725 0.10662376 0.125032   0.13171172 0.1278112
 0.11588271 0.09928586 0.0817474  0.06687286 0.05757441 0.05555691
 0.06107744 0.07309604 0.08973831]
T =  [0.25410913 0.28396992 0.31910239 0.35416219 0.38345606 0.40382198
 0.41606473 0.42368556 0.43060359 0.43973932 0.45268429 0.46986983
 0.49079939 0.51422889 0.53835181 0.56107641 0.58041934 0.59493202
 0.60400302 0.60791226 0.60763662]
A =  [0.58228842 0.60789335 0.62783218 0.63223419 0.616187   0.5826982
 0.54047387 0.49856719 0.46277265 0.43522868 0.41560399 0.40231897
 0.39331791 0.38648525 0.37990079 0.37205073 0.36200625 0.34951106
 0.33491954 0.3189917  0.30262507]


As we can see, RTA3C is returning None arrays where RTA is working well. The difference between both is the number of layers ! RTA3C works for a maximum of 3 layers where RTA works for any number (be raisonable) !

[Chapter 2](SolPOC_Chapter_2.ipynb)